// 微前端/qiankun-micro-app1/src/layout/index.jsx
import React from "react";
import { Outlet } from "react-router-dom";
import { Layout } from "antd";

import Headers from "./components/header";
import Asides from "./components/aside";
import { HeaderWrapper } from "./style";
const { Header, Sider, Content } = Layout;

export default function myLayout() {
  const isQiankun = window.__POWERED_BY_QIANKUN__;
  return (
    <HeaderWrapper>
      {isQiankun ? (
        <Layout>
          <Content>
            <Outlet />
          </Content>
        </Layout>
      ) : (
        <Layout>
          <Header>
            <Headers />
          </Header>
          <Layout>
            <Sider>
              <Asides />
            </Sider>
            <Content>
              <Outlet />
            </Content>
          </Layout>
        </Layout>
      )}
    </HeaderWrapper>
  );
}

// 微前端/qiankun-micro-app2/src/layout/index.vue
<template>
  <div class="common-layout">
    <el-container v-if="isQiankun">
      <el-main>
        <router-view />
      </el-main>
    </el-container>

    <el-container v-else>
      <el-header>
        <Header />
      </el-header>
      <el-container>
        <el-aside width="200px">
          <Aside />
        </el-aside>
        <el-main>
          <router-view />
        </el-main>
      </el-container>
    </el-container>
  </div>
</template>
<script setup>
import Header from "./modules/Header.vue";
import Aside from "./modules/Aside.vue";
const isQiankun = window.__POWERED_BY_QIANKUN__;
</script>

<style scoped>
.common-layout {
  height: 100%;
  .el-header {
    padding: 0;
  }
  .el-aside {
    height: 503px;
  }
}
</style>
